dependencies:
- name: bdd-gh-1585550442
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: bdd-ghfjxy-import-1585552487
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: bdd-nh-1585550442
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: bdd-sbhg-1585550442
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: bdd-sbhg-import-1585552487
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: bdd-sbrp-import-1585552487
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: bdd-spring-1585549346
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.118
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.118
